### ISSUE TITLE
LLVM Profile Error: Failed to write file "default. profraw": Operation not permitted error: unable to open output file '/var/folders/…

### ISSUE THREAD

**Issue by capnslipp** [schwa/MetalCompilerPlugin#3]
Infrequently causes build errors like:

```
LLVM Profile Error: Failed to write file "default. profraw": Operation not permitted error: unable to open output file '/var/folders/_
_s/z9z3sf_17xzfgzh64k6dx2_40000gn/C/clang/ModuleCache/BUC9JS2T5833/metal_types-UE83ZGITDR8A.pcm': 'Operation not permitted"
‹built-in>:1:10: fatal error: could not build module 'metal_types'
#include "metal_types"
error: unable to open output file '/var/folders/_s/z9z3sf_17xzfgzh64k6dx2_40000gn/C/clang/ModuleCache/BUC9JS2T5833/metal_stdlib-UE83ZGITDR8A. pcm': 'Operation not permitted'
3 errors generated.
error:
unable to open output file '/var/folders/_s/z9z3sf_17xzfgzh64k6dx2_40000gn/C/clang/ModuleCache/BUC9JS2T5833/metal_types-UE83ZGITDR8A.pcm': 'Operation not permitted'
‹built-in>:1:10: fatal error: could not build module 'metal_types'
#include "metal_types"
error:
unable to open output file '/var/folders/_s/z9z3sf_17xzfgzh64k6dx2_40000gn/C/clang/ModuleCache/BUC9JS2T5833/metal_stdlib-UE83ZGITDR8A. pcm': 'Operation not permitted'
3 errors generated.
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
```

Sometimes building again resolves the issue, but sometimes (especially on devs' machines with a fresh pull-down of the using project), there's no way to build no matter how much trashing-`DerivedData` or restarting they do.

Has been happening since at least Xcode 15.0 on macOS Sonoma 14.0.

---

This seems like a known issue with SPM build tools without any resolution (according to a quick search ending in the Apple Developer forums).  Perhaps it's caused by the temp folder not existing yet when the `sandbox-exec`-prefixed command that gives permission to the temp folder to the build script that runs `MetalCompilerTool`?  IDK what the solution would be… can you run `MetalCompilerTool` with a no-op argument first to get the temp folder to be created, then a 2nd time to actually do the work?  This might be something we have to wait on SPM to fix.

**Comment by schwa** [comment]
Sounds like a quick fix might be to modify the source to run the command twice and only hard fail if the 2nd run errors.

A bit weird and I'd classify it as a hack… but if it works… I haven't seen the error locally but the source to the plugin is just a single function - easy enough to modify and test maybe?

**Comment by capnslipp** [comment]
Again, seems like a bug in SPM/Xcode that they'll hopefully fix eventually: https://forums.developer.apple.com/forums/thread/725474  So less of a hack and more of a workaround (if my proposed solution works— which is just a guess).

The easiest way to repro I've found is to create a new user on your computer, and do a fresh checkout & build with that user.

I'm sorry I can't help further— we have team members who can't build the project at all no matter what they try, so we've migrated away from using MetalCompilerPlugin.  Best of luck.

**Comment by adarhef** [comment]
I just bumped into this myself. Other people on the team were getting this error on fresh clones of my repo. 
After upgrading to Xcode 15.3 it now just started happening to me as well with absolutely nothing working to get around it.

@capnslipp If you found another way to debug Metal shaders in packages, I'd love to hear about it. This was the only way I could ever get it working.

**Comment by capnslipp** [comment]
@adarhef I didn't.  We switched to having 2 parallel xcodeprojs, one has all the source as a member SPM package (under the project in the project navigator), and the other has the same sources set up to build frameworks with framework targets.  The latter is better for Metal shader debugging (and is used for final release build of the xcframeworks we distribute), the former is more reliable at showing Swift source errors/warnings and breakpoint debugging working properly.  Such is the state of Xcode and Apple's toolchains.  ¯\_(ツ)_/¯

**Comment by adarhef** [comment]
@capnslipp I have some good news.
I took a few hours to dig into this after re-enabling the plugin and looking into what was happening.
I was getting very inconsistent behavior in general.

My project was running fine with the plugin in Xcode and when running `swift test` on my development machine. On my CI machine `swift test` was failing because of the wretched error.
I cloned this repo. Running `swift test` in the command line to run the tests worked fine (although it fails for a different reason not related to shader compilation), and in Xcode it fails with our normal error.

Googling intensely I realized this might be a sandboxing issue. I tried adding the `--disable-sandbox` option on my CI machine when running `swift test`, and remarkably, the error went away.
My understanding is that the Metal compiler runs subprocesses, and those are sandboxed by default now. I heard talk that this behavior was not enforced properly previously and in more recent Xcode versions this was fixed.

I have `ENABLE_USER_SCRIPT_SANDBOXING` set to `YES` on my Xcode project and I'm having no issues on my development machine. If with your Xcode projects you have this enabled as well and are seeing this error, might be worth trying to disable this.

If I'm right and this is indeed a sandboxing issue, I don't think there's much that can be done from within the plugin, unless there's a way to define the module cache locations as input/output paths or something of the sort.

**Comment by schwa** [comment]
Hi Adar, that's really interesting. I've been seeing this issue myself a little when switching targets in a project. Next time I encounter it I'll see if this fixes it and if so - add it to the project README. Cheers.

**Comment by schwa** [comment]
I have a GitHub action failing with this issue and setting ENABLE_USER_SCRIPT_SANDBOXING to either NO or YES seems to make no difference.

**Comment by schwa** [comment]
Looking at the errors generated above (and in my failing GitHub action) and the output of `xcrun metal` I wonder if we can use ` -fmodules-cache-path` to set the cache path to something we're allowed to write to. I'll experiment.

**Comment by schwa** [comment]
I merged this PR in today. It's been working great for me and has solved the issue for me at least.

**Comment by adarhef** [comment]
I removed the `--disable-sandbox` flag from my `swift test` command and it now passes on my CI machine, which didn't happen before. It looks like this might have been the root issue.
Thank you for looking into this! It's super helpful. I rely on this plugin very much.
